spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sparta_scheduler
    username: root
    password: duswn12#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      platform: mysql
      mode: always