spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sparta_scheduler
    username: root
    password: duswn12#
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true